---
- name: Install dependencies
  apt:
    name:
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-pulseaudio

- include_tasks: install.yml

- name: Create gmrender-resurrect user
  user:
    name: "{{ gmrender_resurrect_user }}"
    groups:
      - pulse-access
      - audio
    append: True

- name: Create gmrender-resurrect service
  template:
    src: gmrender-resurrect.service.j2
    dest: /etc/systemd/system/gmrender-resurrect.service
  notify:
    - Reload systemd configuration
    - Restart gmrender-resurrect service

- meta: flush_handlers

- name: Enable gmrender-resurrect service
  service:
    name: gmrender-resurrect
    enabled: True
    state: started
